In [9]:
# Data Load 
import pandas as pd
import os, glob
processed_files_path = 'processed_data'
processed_files = glob.glob(os.path.join(processed_files_path , "*.csv"))


li = []
for filename in processed_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

commits_df = pd.concat(li, axis=0, ignore_index=True)

In [33]:
processed_files


['processed_data\\dropwizard_dropwizard.csv',
 'processed_data\\eBay_parallec.csv',
 'processed_data\\gradle_tooling-commons.csv',
 'processed_data\\GrammarViz2_grammarviz2_src.csv',
 'processed_data\\jMotif_GI.csv',
 'processed_data\\jMotif_SAX.csv',
 'processed_data\\ksclarke_solr-iso639-filter.csv',
 'processed_data\\mtsar_mtsar.csv',
 'processed_data\\steve-community_steve.csv',
 'processed_data\\tracee_contextlogger.csv',
 'processed_data\\zixpo_candybar.csv']

In [34]:
commits_df = commits_df.loc[:, (commits_df != 0).any(axis=0)].fillna(0.0)

print(commits_df.shape)

(11556, 76)


In [11]:
#import seaborn
#seaborn.pairplot(commits_df.drop('LABEL', axis = 1))

In [12]:
from sklearn.model_selection import train_test_split
X = commits_df.drop(['LABEL'], axis = 1)
y = commits_df['LABEL']
training, testing, training_labels, testing_labels = train_test_split(X, y, test_size = .25, random_state = 42)

In [13]:
from sklearn.preprocessing import StandardScaler
# Normalize the data
sc = StandardScaler()
normed_train_data = pd.DataFrame(sc.fit_transform(training), columns = X.columns)
normed_test_data = pd.DataFrame(sc.fit_transform(testing), columns = X.columns)

In [14]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score, balanced_accuracy_score
import numpy as np
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,f1_score,roc_auc_score,precision_score,recall_score,balanced_accuracy_score

names = [
    "Nearest Neighbors",
    "Gaussian Process",
    "Decision Tree",
    "Random Forest",
    "Neural Net",
    "AdaBoost",
    "Naive Bayes",
    "QDA",
    "Logistic Regression",
    "Ridge Classifier",
    "Linear SVM",
    "RBF SVM",
]

classifiers = [
    KNeighborsClassifier(3),
    GaussianProcessClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    MLPClassifier(hidden_layer_sizes=(100,100)),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis(),
    LogisticRegression(),
    RidgeClassifier(),
    SVC(kernel="linear",max_iter=100),
    SVC(max_iter=100),
]


In [15]:
classifiers_perf = []
for clf in classifiers:
    
    clf.fit(normed_train_data, training_labels)
    preds = clf.predict(normed_test_data)
    
    print(clf)
    print(classification_report(testing_labels,preds))
    print(confusion_matrix(testing_labels, preds))
    classifiers_perf.append({
        "classifier":clf,
        "accuracy_score":accuracy_score(testing_labels,preds),
        "balanced_accuracy_score":balanced_accuracy_score(testing_labels,preds),
        "f1_score":f1_score(testing_labels,preds),
        "roc_auc_score":roc_auc_score(testing_labels,preds),
        "precision_score":precision_score(testing_labels,preds),
        "recall_score":recall_score(testing_labels,preds),
        })

KNeighborsClassifier(n_neighbors=3)
              precision    recall  f1-score   support

           0       0.95      0.98      0.96      2678
           1       0.56      0.39      0.46       211

    accuracy                           0.93      2889
   macro avg       0.76      0.68      0.71      2889
weighted avg       0.92      0.93      0.93      2889

[[2614   64]
 [ 128   83]]
GaussianProcessClassifier()
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      2678
           1       0.87      0.34      0.49       211

    accuracy                           0.95      2889
   macro avg       0.91      0.67      0.73      2889
weighted avg       0.94      0.95      0.94      2889

[[2667   11]
 [ 139   72]]
DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       0.95      0.86      0.90      2678
           1       0.18      0.37      0.24       211

    accuracy                           

c:\Users\debon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\debon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\debon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

LogisticRegression()
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      2678
           1       0.69      0.36      0.47       211

    accuracy                           0.94      2889
   macro avg       0.82      0.67      0.72      2889
weighted avg       0.93      0.94      0.93      2889

[[2645   33]
 [ 136   75]]
RidgeClassifier()
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      2678
           1       0.69      0.35      0.46       211

    accuracy                           0.94      2889
   macro avg       0.82      0.67      0.72      2889
weighted avg       0.93      0.94      0.93      2889

[[2644   34]
 [ 137   74]]
SVC(kernel='linear', max_iter=100)
              precision    recall  f1-score   support

           0       0.89      0.07      0.13      2678
           1       0.07      0.89      0.13       211

    accuracy                           0.13      2889


c:\Users\debon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:301: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


In [25]:
pd.DataFrame(classifiers_perf)

classifier  accuracy_score  \
0                 KNeighborsClassifier(n_neighbors=3)        0.933541   
1                         GaussianProcessClassifier()        0.948079   
2                            DecisionTreeClassifier()        0.828314   
3   (DecisionTreeClassifier(max_features='sqrt', r...        0.948425   
4        MLPClassifier(hidden_layer_sizes=(100, 100))        0.947733   
5   (DecisionTreeClassifier(max_depth=1, random_st...        0.938733   
6                                        GaussianNB()        0.926964   
7                     QuadraticDiscriminantAnalysis()        0.926964   
8                                LogisticRegression()        0.941502   
9                                   RidgeClassifier()        0.940810   
10                 SVC(kernel='linear', max_iter=100)        0.129110   
11                                  SVC(max_iter=100)        0.378332   

    balanced_accuracy_score  f1_score  roc_auc_score  precision_score  \
0                  0.684733  0.463687       0.684733         0.564626   
1                  0.668562  0.489796       0.668562         0.867470   
2                  0.617060  0.239264       0.617060         0.176871   
3                  0.670932  0.494915       0.670932         0.869048   
4                  0.670559  0.491582       0.670559         0.848837   
5                  0.626411  0.383275       0.626411         0.723684   
6                  0.500000  0.000000       0.500000         0.000000   
7                  0.500000  0.000000       0.500000         0.000000   
8                  0.671564  0.470219       0.671564         0.694444   
9                  0.669007  0.463950       0.669007         0.685185   
10                 0.477855  0.129412       0.477855         0.069802   
11                 0.535880  0.144762       0.535880         0.080466   

    recall_score  
0       0.393365  
1       0.341232  
2       0.369668  
3       0.345972  
4       0.345972  
5       0.260664  
6       0.000000  
7       0.000000  
8       0.355450  
9       0.350711  
10      0.886256  
11      0.720379

In [17]:
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(training, training_labels)

RandomForestClassifier()

In [18]:
print(clf.__str__())

RandomForestClassifier()


In [19]:
preds = clf.predict(testing)

In [20]:
print (clf.score(training, training_labels))
print(clf.score(testing, testing_labels))


0.9696550132687204
0.9425406715126341


In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(accuracy_score(testing_labels,preds))
print(classification_report(testing_labels,preds))
print(confusion_matrix(testing_labels, preds))

0.9425406715126341
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      2678
           1       0.71      0.36      0.47       211

    accuracy                           0.94      2889
   macro avg       0.83      0.67      0.72      2889
weighted avg       0.93      0.94      0.93      2889

[[2648   30]
 [ 136   75]]


In [27]:
pd.DataFrame(clf.feature_importances_, index=training.columns).sort_values(by=0, ascending=False).head(10)

0
SIZE_LA      0.172635
CM_readme    0.113063
SIZE_LD      0.112086
DIFF_ND      0.071394
CM_update    0.060201
DIFF_EN      0.059356
CM_script    0.039796
CM_updating  0.037406
CM_release   0.035114
DIFF_NF      0.033146